# Generated by Django 3.2.8 on 2023-01-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.IntegerField(verbose_name='College ID')),
                ('college_name', models.CharField(max_length=300, verbose_name='College Name')),
                ('college_address', models.CharField(max_length=550, verbose_name='College Address')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200, verbose_name='Student ID')),
                ('student_age', models.IntegerField(verbose_name='Student Age')),
                ('student_name', models.CharField(max_length=150, verbose_name='Student Name')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Student Email')),
                ('student_amount', models.FloatField(verbose_name='Student Amount')),
                ('student_address', models.TextField(verbose_name='Student Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.college')),
            ],
        ),
    ]
